name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🐛 Bug Fixes"
    label: "bug"
  - title: "📚 Documentation"
    label: "documentation"
  - title: "🚀 Enhancements"
    label: "enhancement"
  - title: "🔨 Refactorings"
    label: "refactor"
  - title: "🔬 Research"
    label: "research"
  - title: "⬆️ Dependencies"
    collapse-after: 3
    labels:
      - "dependencies"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
prerelease: true
prerelease-identifier: "prerelease"
tag-prefix: "v"
template: |
  $CHANGES

  ## 📋 Other Changes
