name: Bug report
description: Create a report to help us improve.
labels:
  - "bug"
body:
  - type: markdown
    attributes:
      value: |
        :warning: PLEASE FIRST READ THE FAQ [(#1770)](https://github.com/anuraghazra/github-readme-stats/discussions/1770) AND COMMON ERROR CODES [(#1772)](https://github.com/anuraghazra/github-readme-stats/issues/1772)!!!
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description:
        A clear and concise description of what you expected to happen.
  - type: textarea
    attributes:
      label: Screenshots / Live demo link
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Paste the github-readme-stats link as markdown image
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
  - type: markdown
    attributes:
      value: |
        ---
        ### FAQ (Snippet)

        Below are some questions that are found in the FAQ. The full FAQ can be found in [#1770](https://github.com/anuraghazra/github-readme-stats/discussions/1770).

        #### Q: My card displays an error

        **Ans:** First, check the common error codes (i.e. https://github.com/anuraghazra/github-readme-stats/issues/1772) and existing issues before creating a new one. 

        #### Q: How to hide jupyter Notebook?

        **Ans:** `&hide=jupyter%20notebook`.

        #### Q: I could not figure out how to deploy on my own vercel instance

        **Ans:** Please check:
          - Docs: https://github.com/anuraghazra/github-readme-stats/#deploy-on-your-own-vercel-instance
          - YT tutorial by codeSTACKr: https://www.youtube.com/watch?v=n6d4KHSKqGk&feature=youtu.be&t=107

        #### Q: Language Card is incorrect

        **Ans:** Please read these issues/comments before opening any issues regarding language card stats:
          - https://github.com/anuraghazra/github-readme-stats/issues/136#issuecomment-665164174
          - https://github.com/anuraghazra/github-readme-stats/issues/136#issuecomment-665172181

        #### Q: How to count private stats?

        **Ans:** We can only count private commits & we cannot access any other private info of any users, so it's impossible. The only way is to deploy on your own instance & use your own PAT (Personal Access Token).
