name: Feature request
description: Suggest an idea for this project
body:
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: >-
        A clear and concise description of what the problem is. Ex. I'm always
        frustrated when [...]
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: >-
        A clear and concise description of any alternative solutions or features
        you've considered.
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
  - type: markdown
    attributes:
      value: >-
        PLEASE READ THE FAQs!!!


        Q: How to hide jupyter Notebook?


        Ans: &hide=jupyter%20notebook


        Q: I could not figure out how to deploy on my own vercel instance


        Ans:
         - docs: https://github.com/anuraghazra/github-readme-stats/#deploy-on-your-own-vercel-instance
         - YT tutorial by codeSTACKr: https://www.youtube.com/watch?v=n6d4KHSKqGk&feature=youtu.be&t=107

        Q: Language Card is incorrect


        Ans: Please read all the issues / comments before opening any issues
        regarding language card stats:
          - https://github.com/anuraghazra/github-readme-stats/issues/136#issuecomment-665164174
          - https://github.com/anuraghazra/github-readme-stats/issues/136#issuecomment-665172181

        Q: How to count private stats?


        Ans: We can only count private commits & we cannot access any other
        private info of any users, so it's not possible. only way is to deploy
        on your own instance & use your own PAT (Personal Access Token)