name: Require Pull Request Labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  require-labels:
    if: |
      github.actor != 'github-actions[bot]' &&
      github.actor != 'dependabot[bot]' &&
      github.actor != 'renovate[bot]' && 
      github.actor != 'web-flow'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: "bug,documentation,enhancement,refactor,research"
