name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: read-all

jobs:
  build:
    name: Perform tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install & Test
        run: |
          npm ci
          npm run test

      - name: Run ESLint
        run: |
          npm run lint

      - name: Run bench tests
        run: |
          npm run bench

      - name: Run Prettier
        run: |
          npm run format:check

      - name: Code Coverage
        uses: codecov/codecov-action@e0b68c6749509c5f83f984dd99a76a1c1a231044 # v4.0.1
