name: "Convert new TODOs to GitHub Issues"
on: ["push"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "alstr/todo-to-issue-action@v4"
        env:
          AUTO_ASSIGN: true
